### ISSUE TITLE
How can remap open/close with one keymap

### ISSUE THREAD

**Issue by ayoubelmhamdi** [stevearc/qf_helper.nvim#1]
can i have some intelligent to open or close `Quiqefix` with one `keymaping` like:
```
nnoremap <silent> <leader>t <cmd>AutoToggle!<CR>
```
this option is work better for explorer of nvim `:Lexpolore`

**Comment by stevearc** [comment]
Sure, to toggle the quickfix you can do
```
nnoremap <silent> <leader>q <cmd>QFToggle!<CR>
```
