### ISSUE TITLE
Feature request: Add position indicator output to cmdline

### ISSUE THREAD

**Issue by ghillb** [stevearc/qf_helper.nvim#3]
Hi,

with using `:cnext`, `:cprevious`, `:lnext` & `:lprevious` you get an indicator showing the position in list and the current line's content.
![image](https://user-images.githubusercontent.com/35503959/142723644-117fd561-d279-455a-86c9-c4bce742bec9.png)
Unfortunately the native cycling doesn't loop around at the end/beginning of the list.

With this plugin there is no such output, when cycling with `:QFPrev`, `:QFNext`, `:LLPrev`, `:LLNext`.
Any chance you would consider implementing a similar indicator?

**Comment by stevearc** [comment]
Yeah, I think that's a pretty good nice-to-have feature. Interestingly, I do not see that indicator nor do I think I ever have. Do you have any idea if it's behind a config option?

**Comment by ghillb** [comment]
I tried the following:

Started nvim 5.1 with `nvim -u NONE` and populated the qf list with `:vim/<some_string>/ **/*`.
After that I'm still able to see the indicator, when executing `cnext` & `cprevious`.
The same thing works in `vim`.So I think it should be a default built-in.

**Comment by stevearc** [comment]
Ahhhh it only shows up if the quickfix window is closed. Got it, thanks!
