### ISSUE TITLE
Error when `LLToggle!`: `lua/qf_helper.lua:118: Vim(lopen):E776: No location list`

### ISSUE THREAD

**Issue by nyngwang** [stevearc/qf_helper.nvim#4]
### how to reproduce

Very new to qflist & loclist. I copy-paste everything from README.md. Dry run `LLToggle!` with this:

```
vim.keymap.set('n', '<Leader>l', function() vim.cmd('LLToggle!') end, {nowait=true, silent=true,noremap=true})
```

### error message

```
E5108: Error executing lua: /Users/ningwang/.config/nvim/lua/qflist.lua:12: Vim(call):E5108: Error executing lua .../site/pack/packer/start/qf_helper.nvim/lua/qf_helper.lua:118: Vim(lopen):E776: No location lis
t
stack traceback:
        [C]: in function 'cmd'
        .../site/pack/packer/start/qf_helper.nvim/lua/qf_helper.lua:118: in function 'open'
        .../site/pack/packer/start/qf_helper.nvim/lua/qf_helper.lua:131: in function 'toggle'
        [string "luaeval()"]:1: in main chunk
        [C]: in function 'cmd'
        /Users/ningwang/.config/nvim/lua/qflist.lua:12: in function </Users/ningwang/.config/nvim/lua/qflist.lua:12>
stack traceback:
        [C]: in function 'cmd'
        /Users/ningwang/.config/nvim/lua/qflist.lua:12: in function </Users/ningwang/.config/nvim/lua/qflist.lua:12>
```

### debug info

nvim -v:
```
NVIM v0.7.0-dev+953-gd0493d110
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by stevearc** [comment]
This is expected behavior. Vim allows you to open an empty quickfix (`:copen`), but if you try to open the loclist before populating it, it will give you an error. If you try manually running `:lopen` you will see the same error without the stack trace. I've pushed up a commit to hide the stack trace in this situation (but still prints the error message), since it's just useless noise.

**Comment by nyngwang** [comment]
> [...] you will see the same error without the stack trace.

Wow, exactly. I think you can close it for now. Sorry for my stupid issue, I was learning about qflist & loclist.

---

The good news for you: I did learn a lot from reading the source of this plugin. While I didn't get all of them, it did help me improve a lot today. If you don't mind: could I ask more questions about the implementation here? Answer it or not is up to you.

**Comment by stevearc** [comment]
No worries!

> If you don't mind, may I open some issues about the implementation details in the future?

If you're reporting bugs or asking for features, then feel free to open issues. If you simply have questions about the implementation, put it in [the discussions section](https://github.com/stevearc/qf_helper.nvim/discussions)

**Comment by nyngwang** [comment]
@stevearc: Cool stuff! Never know about this feature. OK, I will put things there :)
