### ISSUE TITLE
QNext leads to 'Press ENTER or type command to continue'

### ISSUE THREAD

**Issue by astier** [stevearc/qf_helper.nvim#9]
Whenever I execute QNext while being on the last quickfix-entry (so I jump back to the first entry) vim says `Press ENTER or type command to continue`.  Then I have to press Enter before the cursor actually jumps to the next/first entry. That's a little bit inconvenient. Is it possible to disable it? Great plugin and thanks.

**Comment by stevearc** [comment]
I'm not able to reproduce this. I'm using a minimal init.lua file

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  { "stevearc/qf_helper.nvim", config = true },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

I'm saving this in the `qf_helper.nvim` directory and loading it with
`nvim -u repro.lua -c 'grep -IR quickfix lua' -c '22cc'`
Which opens Neovim with a quickfix list and selects the last item. If I then run `:QNext`, I don't see the message you're describing.

Could you help find a configuration that does reproduce the issue?

**Comment by astier** [comment]
Cant reproduce anymore. It didn't happen always. Just sometimes under unknown conditions. I will let you know if it happens again.
